version: '3'
services:
  termometer-simulator:
    build:
      context: ./devices/termometer
      dockerfile: Dockerfile
    container_name: termometer-simulator
    restart: always
    depends_on:
      - rabbitmq
      - cassandra
    links:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    volumes:
      - termometer-data:/app/data  # Zarejestrowany wolumen dla termometer-simulator

  distributor-app:
    build:
      context: ./distributorApp
    container_name: distributor-app
    restart: always
    depends_on:
      - cassandra
      - rabbitmq
      - termometer-simulator  # Dodajemy zależność od termometer-simulator
    environment:
      CASSANDRA_HOSTS: cassandra  # Adres hosta bazy danych Cassandra
      CASSANDRA_KEYSPACE: devices  # Nazwa przestrzeni kluczy bazy danych Cassandra
      RABBITMQ_URL: amqp://rabbitmq:5672/  # URL RabbitMQ
      QUEUE: devices  # Nazwa kolejki RabbitMQ

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Port do RabbitMQ
      - "15672:15672"  # Port do RabbitMQ Management (interfejs webowy)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  cassandra:
    image: "cassandra:latest"
    container_name: cassandra
    ports:
      - "9042:9042"  # Port do Cassandra
      - "9160:9160"  # Port do Cassandra Thrift
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch

volumes:
  rabbitmq_data:
  cassandra_data:
  termometer-data:  # Zarejestrowany wolumen dla termometer-simulator
